AgricultureManagementSystem/Controllers/CombineController.cs
using AgricultureManagementSystem.Data;
using AgricultureManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace AgricultureManagementSystem.Controllers
{
    public class CombineController : Controller
    {
        private readonly ApplicationDbContext db;

        public CombineController(ApplicationDbContext db)
            => this.db = db;

        public IActionResult Index()
            => View(db.Combines);

        public IActionResult Details(int id)
        {
            if (id != 0)
            {
                Combine combine = db.Combines
                    .Where(c => c.Id == id)
                    .Include(c => c.Headers)
                    .Include(c => c.Services)
                    .FirstOrDefault();

                if (combine != null)
                {
                    return View(combine);
                }
            }

            return NotFound();
        }

        public IActionResult Create()
            => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Combine combine)
        {
            if (ModelState.IsValid)
            {
                db.Combines.Add(combine);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(combine);
        }

        public IActionResult Edit(int id)
        {
            if (id != 0)
            {
                var item = db.Combines.Find(id);
                if (item != null)
                    return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Combine combine)
        {
            if (ModelState.IsValid)
            {
                db.Combines.Update(combine);
                db.SaveChanges();
                return RedirectToAction(nameof(Details),
                    new { id = combine.Id });
            }

            return View(combine);
        }

        public IActionResult Delete(int id)
        {
            if (id != 0)
            {
                var item = db.Combines.Find(id);
                if (item != null)
                    return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            if (id != 0)
            {
                var item = db.Combines
                    .Where(c => c.Id == id)
                    .Include(c => c.Headers)
                    .Include(c => c.Services)
                    .FirstOrDefault();

                if (item != null)
                {
                    db.Combines.Remove(item);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }

            return NotFound();
        }

        public IActionResult CreateHeader()
            => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateHeader(int combineId, Header header)
        {
            if (ModelState.IsValid)
            {
                if (combineId != 0)
                {
                    Combine combine = db.Combines
                        .Where(c => c.Id == combineId)
                        .Include(c => c.Headers)
                        .FirstOrDefault();

                    if (combine != null)
                    {
                        combine.Headers.Add(header);
                        db.SaveChanges();
                        return RedirectToAction(nameof(Details),
                            new { id = combineId });
                    }
                }

                return NotFound();

            }

            return View(header);
        }

        public IActionResult EditHeader(int id, int combineId)
        {
            if (id != 0 && combineId != 0)
            {
                Combine combine = db.Combines
                    .Where(c => c.Id == combineId)
                    .Include(c => c.Headers)
                    .FirstOrDefault();

                if (combine != null)
                {
                    try
                    {
                        Header header = combine.Headers
                            .Single(h => h.Id == id);
                        return View(header);
                    }
                    catch { }
                }
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditHeader(Header header, int combineId)
        {
            if (ModelState.IsValid)
            {
                if (combineId != 0)
                {
                    Combine combine = db.Combines
                        .Where(c => c.Id == combineId)
                        .Include(c => c.Headers)
                        .FirstOrDefault();

                    if (combine != null)
                    {
                        int headerListIndex = combine.Headers.ToList()
                            .FindIndex(h => h.Id == header.Id);

                        try
                        {
                            combine.Headers[headerListIndex].Update(header);

                            db.SaveChanges();

                            return RedirectToAction(nameof(Details),
                                new { id = combineId });
                        }
                        catch { }
                    }
                }

                return NotFound();

            }

            return View(header);
        }

        public IActionResult DeleteHeader(int id, int combineId)
        {
            if (id != 0 && combineId != 0)
            {
                Combine combine = db.Combines
                    .Where(c => c.Id == combineId)
                    .Include(c => c.Headers)
                    .FirstOrDefault();

                if (combine != null)
                {
                    try
                    {
                        Header header = combine.Headers
                            .Single(h => h.Id == id);
                        return View(header);
                    }
                    catch { }
                }
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteHeaderPost(int id, int combineId)
        {
            if (id != 0 && combineId != 0)
            {
                Combine combine = db.Combines
                    .Where(c => c.Id == combineId)
                    .Include(c => c.Headers)
                    .FirstOrDefault();

                if (combine != null)
                {
                    try
                    {
                        Header header = combine.Headers
                            .Single(h => h.Id == id);

                        combine.Headers.Remove(header);
                        db.SaveChanges();

                        return RedirectToAction(nameof(Details),
                            new { id = combineId });
                    }
                    catch { }
                }
            }

            return NotFound();
        }
    }
}

AgricultureManagementSystem/Controllers/FieldController.cs
using AgricultureManagementSystem.Data;
using AgricultureManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace AgricultureManagementSystem.Controllers
{
    public class FieldController : Controller
    {
        private readonly ApplicationDbContext db;

        public FieldController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
            => View(db.Fields);

        public IActionResult Details(int id)
        {
            if (id != 0)
            {
                var item = db.Fields
                    .Where(f => f.Id == id)
                    .Include(f => f.Activities)
                    .FirstOrDefault();

                if (item != null)
                {
                    return View(item);
                }
            }

            return NotFound();
        }

        public IActionResult Create()
            => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Field field)
        {
            if (ModelState.IsValid)
            {
                db.Fields.Add(field);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(field);
        }

        public IActionResult Edit(int id)
        {
            if (id != 0)
            {
                var item = db.Fields.Find(id);
                if (item != null)
                    return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Field field)
        {
            if (ModelState.IsValid)
            {
                db.Fields.Update(field);
                db.SaveChanges();
                return RedirectToAction(nameof(Details),
                    new { id = field.Id });
            }

            return View(field);
        }

        public IActionResult Delete(int id)
        {
            if (id != 0)
            {
                var item = db.Fields.Find(id);
                if (item != null)
                    return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            if (id != 0)
            {
                var item = db.Fields
                    .Where(f => f.Id == id)
                    .Include(f => f.Activities)
                    .FirstOrDefault();

                if (item != null)
                {
                    db.Fields.Remove(item);
                    db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }

            return NotFound();
        }
    }
}

AgricultureManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - System zarządzania gospodarstwem rolnym</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Shutdown">Wyłącz aplikację</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tractor" asp-action="Index">Traktory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Combine" asp-action="Index">Kombajny</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Machine" asp-action="Index">Maszyny</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trailer" asp-action="Index">Przyczepy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Field" asp-action="Index">Pola uprawne</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Notatki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Finance" asp-action="Index">Finanse</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            2021 - 2022&emsp;AMS - System zarządzania gospodarstwem rolnym &copy; Jakub Malinowski
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>

AgricultureManagementSystem/Views/Shared/_ServicePartial.cshtml
@model AgricultureManagementSystem.Models.Equipment

<div id="service-partial" class="mt-4">
    @{
        var routeParams = new Dictionary<string, string>
    {
            { "equipmentId", Model.Id.ToString() },
            { "equipmentType", Model.GetType().Name }

        };
    }
    <h4>Czynności serwisowe</h4>
    <div>
        <a class="btn btn-success" asp-controller="Service"
           asp-action="Create" asp-all-route-data="routeParams">Dodaj</a>
    </div>
    <div class="mt-3">
        @if (Model.Services.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th class="align-middle border-bottom-0">
                            @Html.DisplayNameFor(model => model.Services[0].DateTime)
                        </th>
                        <th class="align-middle border-bottom-0">
                            @Html.DisplayNameFor(model => model.Services[0].ServiceType)
                        </th>
                        <th class="align-middle border-bottom-0">
                            @Html.DisplayNameFor(model => model.Services[0].ServiceDescription)
                        </th>
                        <th class="border-bottom-0"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var service in Model.Services
                       .OrderByDescending(s => s.DateTime))
                    {
                        <tr id="service-partial-@service.Id">
                            <td>
                                @Html.DisplayFor(modelItem => service.DateTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => service.ServiceType)
                            </td>
                            <td class="multiline-text">@Html.DisplayFor(modelItem => service.ServiceDescription)</td>
                            <td class="btn-group-vertical">
                                <a class="btn btn-outline-warning btn-sm"
                                   asp-controller="Service"
                                   asp-action="Edit"
                                   asp-all-route-data="routeParams"
                                   asp-route-id="@service.Id">Edytuj</a>
                                <a class="btn btn-outline-danger btn-sm"
                                   asp-controller="Service"
                                   asp-action="Delete"
                                   asp-all-route-data="routeParams"
                                   asp-route-id="@service.Id">Usuń</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Brak danych serwisowych.</p>
        }
    </div>
</div>
<script>highlightServiceRow(window.location.hash.substring(17))</script>